### ISSUE TITLE
MPRIS2 integration and Multimedia keys not working anymore with Qobuz

### ISSUE THREAD

**Issue by bpresles** [tiliado/nuvola-app-qobuz#6] opened 2020-07-06 12:03 UTC
I don't know if it's due to a change on Qobuz API or something else, but since a few weeks I noticed that multimedia keys and MPRIS2 integration stopped working with Qobuz as you can see on this screenshot

![image](https://user-images.githubusercontent.com/220623/86591218-6a220900-bf91-11ea-954f-c04da5d2a946.png)

**Comment by fenryxo** [comment] 2020-07-06 15:55
Closing as duplicate of tiliado/nuvolaruntime#619

**Closed by fenryxo** 2020-07-06 15:55 UTC
